@startuml
class Category {
    +int category_id
    +String category_name
    +Category(String category_name) <<constructor>>
    +add_category()
    +remove_category()
    +search_and_filtering()
    +update_category()
}

class Book {
    +int book_id
    +String title
    +String author
    +String isbn
    +Date year_edition
    +int category_id_categories
    +Book(String title, String author, String isbn, Date year_edition, int category_id) <<constructor>>
    +create_book()
    +check_duplicate_book()
    +update_book_data()
    +delete_book()
    +query_books()
}

class User {
    +int user_id
    +String dni
    +String user_name
    +String user_lastname
    +String mail
    +String phone
    +User(String dni, String user_name, String user_lastname, String mail, String phone) <<constructor>>
    +check_user()
    +create_user()
    +update_user()
    +delete_user()
    +search_users()
}

class LibraryLoan {
    +int loan_id
    +int book_id
    +int user_id
    +Date entry_date
    +Date return_date
    +LibraryLoan(int book_id, int user_id, Date entry_date, Date return_date) <<constructor>>
    +create_loan()
    +read_loan()
    +update_loan()
    +delete_loan()
    +end_loan()
    +notify_return_date()
    +return_delay_alert()
    +notify_delay_date()
}

Category "1" -- "0..*" Book : contains
Book "1" -- "0..*" LibraryLoan : loaned by
User "1" -- "0..*" LibraryLoan : borrows
@enduml
